---
kind: pipeline
type: docker
name: default

concurrency:
  limit: 1

trigger:
  branch:
  - master

volumes:
- name: dot-aws
  temp: {}

steps:

- name: files_changed
  image: alpine:3
  commands:
  - apk add git
  - |-
    for DIR in $(git --no-pager diff --name-only $DRONE_COMMIT_BEFORE..$DRONE_COMMIT_AFTER | sed "s/^\\(\\.\\/\\)*\\(.*\\)/\\2/" | sed "s/^\\(.*\\)\\/.*/\\1/" | sort | uniq ); do
      for VERSION in $(find . -name terraform.version | sed "s/^\\(\\.\\/\\)*\\(.*\\)/\\2/" | sed "s/^\\(.*\\)\\/.*/\\1/" | sort | uniq); do
        case "$DIR" in
          "$VERSION"*)
            echo $VERSION >> terraform_dirs
            echo "INFO  Adding $VERSION to terrafom_dirs";;
        esac
      done
    done

- name: aws_credentials
  image: amazon/aws-cli:2.0.31
  volumes:
  - name: dot-aws
    path: /root/.aws
  environment:
    ASSUME_ROLE_EXTERNAL_ID:
      from_secret: assume_role_external_id
    AWS_ACCOUNT_ID:
      from_secret: demo_account_id
  commands:
  - aws configure set role_arn "arn:aws:iam::$AWS_ACCOUNT_ID:role/DroneTerraformContainerDays"
  - aws configure set region eu-west-1
  - aws configure set credential_source Ec2InstanceMetadata
  - aws configure set external_id $ASSUME_ROLE_EXTERNAL_ID
  - aws sts get-caller-identity

- name: terraform_${DRONE_BUILD_EVENT}
  image: alpine:3
  volumes:
  - name: dot-aws
    path: /root/.aws
  environment:
    # workaround for https://github.com/terraform-providers/terraform-provider-aws/issues/5018
    AWS_METADATA_URL: http://localhost/not/existent/url
    # workaround for https://github.com/hashicorp/aws-sdk-go-base/issues/7
    AWS_SDK_LOAD_CONFIG: 1
  commands:
  - apk add bash curl git
  - git clone --branch v1.0.2 https://github.com/tfutils/tfenv.git /opt/tfenv
  - ln -s /opt/tfenv/bin/* /usr/local/bin
  - |-
    ROOT_DIR=$(pwd)
    for DIR in $(cat terraform_dirs); do
      echo "INFO  Changing to $DIR"
      cd $ROOT_DIR/$DIR
      tfenv install $(cat terraform.version)
      tfenv use $(cat terraform.version)
      terraform init
      if [ "$DRONE_BUILD_EVENT" == "pull_request" ]; then
        terraform plan
      elif [ "$DRONE_BUILD_EVENT" == "push" ]; then
        terraform apply
      fi
    done
